/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author ThienDinh
 */
public class SearchForm extends javax.swing.JFrame {

    public static boolean hideAbleForm;
    private AHDictionaryDotCom searchEngine;
    private DictionaryDotCom exampleEngine;
    private int history;
    private String definition;
    private String example;
    private Dimension defaultDimension;
    private Thread audioThread;
    private int countAudio;
    private JLabel[] labels;
    //private boolean hideAbleForm;

    /**
     * Creates new form SearchForm
     */
    public SearchForm() {
        hideAbleForm = true;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        searchEngine = new AHDictionaryDotCom();
        exampleEngine = new DictionaryDotCom();
        defaultDimension = this.getSize();
        Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(this.defaultDimension);
        this.setLocation(screen.width - this.getWidth(),
                screen.height / 2 - this.getHeight() / 2);
        this.btnRead.setEnabled(false);
        JLabel[] labelList = {lbWord0, lbWord1, lbWord2, lbWord3, lbWord4, lbWord5, lbWord6, lbWord7, lbWord8};
        labels = labelList;
    }

    private boolean checkLabelExistance(String word) {
        for (JLabel label : labels) {
            if (label.getText().equals(word)) {
                return true;
            }
        }
        return false;
    }

    private void placeInHistory(String word) {
        Font newFont = new Font("Segoe UI", Font.BOLD, 12);
        Font oldFont = new Font("Segoe UI", Font.PLAIN, 12);
        labels[history].setFont(newFont);
        if (history == 0) {
            labels[labels.length - 1].setFont(oldFont);
        } else {
            labels[history - 1].setFont(oldFont);
        }
        labels[history].setText(word);
        if (++history == labels.length) {
            history = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lbPowered = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtWord = new javax.swing.JTextField();
        btnRead = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnBingImage = new javax.swing.JButton();
        btnBingVideo = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        panel2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        scrlDefinition = new javax.swing.JScrollPane();
        txaDefinition = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaExample = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        lbWord0 = new javax.swing.JLabel();
        lbWord1 = new javax.swing.JLabel();
        lbWord2 = new javax.swing.JLabel();
        lbWord3 = new javax.swing.JLabel();
        lbWord4 = new javax.swing.JLabel();
        lbWord5 = new javax.swing.JLabel();
        lbWord6 = new javax.swing.JLabel();
        lbWord7 = new javax.swing.JLabel();
        lbWord8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elegant Dictionary [tdinhcs@gmail.com]");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbPowered.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lbPowered.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPowered.setText("∞ Powered by Ahdictionary.com and Dictionary.com ∞ ");
        lbPowered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPoweredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPoweredMouseExited(evt);
            }
        });

        panel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel7.setLayout(new java.awt.BorderLayout());

        txtWord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWord.setToolTipText("Right click to paste.");
        txtWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtWord.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtWordCaretUpdate(evt);
            }
        });
        txtWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWordMouseClicked(evt);
            }
        });
        txtWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWordActionPerformed(evt);
            }
        });
        txtWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWordFocusGained(evt);
            }
        });
        txtWord.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtWordInputMethodTextChanged(evt);
            }
        });
        txtWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWordKeyTyped(evt);
            }
        });
        jPanel7.add(txtWord, java.awt.BorderLayout.CENTER);

        btnRead.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnRead.setText("READ");
        btnRead.setToolTipText("Listen to the word's pronunciation.");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        jPanel7.add(btnRead, java.awt.BorderLayout.LINE_END);

        panel1.add(jPanel7);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        btnBingImage.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBingImage.setText("Search IMAGE");
        btnBingImage.setToolTipText("Search images for the word using Bing.");
        btnBingImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBingImageActionPerformed(evt);
            }
        });
        jPanel3.add(btnBingImage);

        btnBingVideo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBingVideo.setText("Search VIDEO");
        btnBingVideo.setToolTipText("Search videos for the word using Bing.");
        btnBingVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBingVideoActionPerformed(evt);
            }
        });
        jPanel3.add(btnBingVideo);

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSearch.setText("Search DEFINITION");
        btnSearch.setToolTipText("Look up definition.");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch);

        panel1.add(jPanel3);

        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        panel2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panel2StateChanged(evt);
            }
        });

        txaDefinition.setEditable(false);
        txaDefinition.setBackground(new java.awt.Color(255, 255, 217));
        txaDefinition.setColumns(20);
        txaDefinition.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txaDefinition.setLineWrap(true);
        txaDefinition.setRows(5);
        txaDefinition.setToolTipText("Select and right click to copy");
        txaDefinition.setWrapStyleWord(true);
        txaDefinition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txaDefinition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txaDefinition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txaDefinitionMouseClicked(evt);
            }
        });
        scrlDefinition.setViewportView(txaDefinition);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlDefinition, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(scrlDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel2.addTab("   Definition   ", jPanel5);

        txaExample.setEditable(false);
        txaExample.setBackground(new java.awt.Color(255, 255, 217));
        txaExample.setColumns(20);
        txaExample.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txaExample.setLineWrap(true);
        txaExample.setRows(5);
        txaExample.setToolTipText("Select and right click to copy");
        txaExample.setWrapStyleWord(true);
        txaExample.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txaExample.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txaExample.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txaExampleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txaExample);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        panel2.addTab("   Example   ", jPanel6);

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Save into today word list");
        btnSave.setToolTipText("Save this word");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        panel3.setBackground(new java.awt.Color(204, 204, 255));
        panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        panel3.setLayout(new java.awt.GridLayout(3, 3));

        lbWord0.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord0.setToolTipText("Right click to select");
        lbWord0.setName("label0"); // NOI18N
        lbWord0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord0MouseClicked(evt);
            }
        });
        panel3.add(lbWord0);

        lbWord1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord1.setToolTipText("Right click to select");
        lbWord1.setName(""); // NOI18N
        lbWord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord1MouseClicked(evt);
            }
        });
        panel3.add(lbWord1);

        lbWord2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord2.setToolTipText("Right click to select");
        lbWord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord2MouseClicked(evt);
            }
        });
        panel3.add(lbWord2);

        lbWord3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord3.setToolTipText("Right click to select");
        lbWord3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord3MouseClicked(evt);
            }
        });
        panel3.add(lbWord3);

        lbWord4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord4.setToolTipText("Right click to select");
        lbWord4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord4MouseClicked(evt);
            }
        });
        panel3.add(lbWord4);

        lbWord5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord5.setToolTipText("Right click to select");
        lbWord5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord5MouseClicked(evt);
            }
        });
        panel3.add(lbWord5);

        lbWord6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord6.setToolTipText("Right click to select");
        lbWord6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord6MouseClicked(evt);
            }
        });
        panel3.add(lbWord6);

        lbWord7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord7.setToolTipText("Right click to select");
        lbWord7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord7MouseClicked(evt);
            }
        });
        panel3.add(lbWord7);

        lbWord8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord8.setToolTipText("Right click to select");
        lbWord8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord8MouseClicked(evt);
            }
        });
        panel3.add(lbWord8);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbPowered, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPowered)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
//        if (this.hideAbleForm) {
//            Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
//            this.setSize(this.getWidth(), 0);
//            this.setLocation(screen.width - 2 * this.getWidth() / 5, screen.height / 2 - 5 * this.getHeight());
//        }
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            this.audioThread.interrupt();
        } catch (Exception ex) {
            System.out.println("formWindowClosing: " + ex.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
//        Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
//        this.setSize(this.defaultDimension);
//        this.setLocation(screen.width - this.getWidth(),
//                screen.height / 2 - this.getHeight() / 3);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        try {
            if (audioThread != null) {
                audioThread.interrupt();
            }
            Audio pronounce = new Audio();
            URL audio = new URL("http://www.ahdictionary.com/application/resources/wavs/"
                    + this.searchEngine.getPronunciation() + ".wav");
            pronounce.setVoiceLink(audio);
            audioThread = new Thread(pronounce, "Pronunciation" + (this.countAudio++));
            audioThread.start();
        } catch (MalformedURLException ex) {
            System.out.println("== URL error!!");
        }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        DailyList list = new DailyList(this.txtWord.getText(), this.defaultDimension);
        list.setVisible(true);
        this.hideAbleForm = false;
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String text = this.txtWord.getText().toLowerCase().trim();
        this.txtWord.setText(text);
        if (!text.equals("")) {
            // Definition
            searchEngine.setWord(text);
            definition = searchEngine.getDefinition();
            this.txaDefinition.setText(definition + "\n");
            // Example
            exampleEngine.setWord(text);
            example = exampleEngine.getExample();
            this.txaExample.setText(example);
            this.btnRead.setEnabled(true);
            // Reset the caret to 0 after the text area updated
            this.txaDefinition.setCaretPosition(0);
            this.txaExample.setCaretPosition(0);
        } else {
            this.txaDefinition.setText("Please input a word for searching!");
        }
        if (this.txaDefinition.getText().equals("")) {
            this.txaDefinition.setText("The program couldn't find \"" + this.txtWord.getText() + "\" in the dictionary!");
            this.txtWord.setText(this.txtWord.getText().trim());
            this.btnRead.setEnabled(false);
        } else if (!this.txtWord.getText().equals("")
                && !checkLabelExistance(this.txtWord.getText())) {
            this.placeInHistory(this.txtWord.getText());
        }
        this.btnSearch.setEnabled(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBingVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBingVideoActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("http://www.bing.com/videos/search?q="
                    + this.txtWord.getText().replaceAll(" ", "+")));
        } catch (Exception ex) {
            this.txaDefinition.setText("The program can not perform this search!");
        }
    }//GEN-LAST:event_btnBingVideoActionPerformed

    private void btnBingImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBingImageActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("http://www.bing.com/images/search?q="
                    + this.txtWord.getText().replaceAll(" ", "+")));
        } catch (Exception ex) {
            this.txaDefinition.setText("The program can not perform this search!");
        }
    }//GEN-LAST:event_btnBingImageActionPerformed

    private void txtWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWordKeyTyped

    private void txtWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWordKeyReleased

    private void txtWordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtWordInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWordInputMethodTextChanged

    private void txtWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWordFocusGained

    private void txtWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWordActionPerformed
        // TODO add your handling code here:
        this.btnSearch.doClick();
    }//GEN-LAST:event_txtWordActionPerformed

    private void txtWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWordMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            try {
                String text = String.valueOf(java.awt.Toolkit.getDefaultToolkit()
                        .getSystemClipboard().getData(DataFlavor.stringFlavor));
                this.txtWord.setText(text);
            } catch (UnsupportedFlavorException ex) {
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_txtWordMouseClicked

    private void txtWordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtWordCaretUpdate
        // TODO add your handling code here:
        this.btnSearch.setEnabled(true);
    }//GEN-LAST:event_txtWordCaretUpdate

    private void lbPoweredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPoweredMouseExited
        // TODO add your handling code here:
        Font font = new Font("Segoe UI", Font.BOLD, 10);
        this.lbPowered.setFont(font);
    }//GEN-LAST:event_lbPoweredMouseExited

    private void lbPoweredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPoweredMouseEntered
        // TODO add your handling code here:
        Font font = new Font("Segoe UI", Font.ITALIC, 10);
        this.lbPowered.setFont(font);
    }//GEN-LAST:event_lbPoweredMouseEntered

    private void lbWord8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord8MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord8.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lbWord8MouseClicked

    private void lbWord7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord7MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord7.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lbWord7MouseClicked

    private void lbWord6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord6MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord6.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lbWord6MouseClicked

    private void lbWord5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord5MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord5.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord5MouseClicked

    private void lbWord4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord4MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord4.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord4MouseClicked

    private void lbWord3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord3MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord3.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord3MouseClicked

    private void lbWord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord2MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord2.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord2MouseClicked

    private void lbWord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord1MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord1.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord1MouseClicked

    private void lbWord0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord0MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord0.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord0MouseClicked

    private void txaDefinitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txaDefinitionMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            StringSelection stringSelection = new StringSelection(this.txaDefinition.getSelectedText());
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, stringSelection);
        }
    }//GEN-LAST:event_txaDefinitionMouseClicked

    private void txaExampleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txaExampleMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            StringSelection stringSelection = new StringSelection(this.txaExample.getSelectedText());
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, stringSelection);
        }
    }//GEN-LAST:event_txaExampleMouseClicked

    private void panel2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panel2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_panel2StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBingImage;
    private javax.swing.JButton btnBingVideo;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPowered;
    private javax.swing.JLabel lbWord0;
    private javax.swing.JLabel lbWord1;
    private javax.swing.JLabel lbWord2;
    private javax.swing.JLabel lbWord3;
    private javax.swing.JLabel lbWord4;
    private javax.swing.JLabel lbWord5;
    private javax.swing.JLabel lbWord6;
    private javax.swing.JLabel lbWord7;
    private javax.swing.JLabel lbWord8;
    private javax.swing.JPanel panel1;
    private javax.swing.JTabbedPane panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JScrollPane scrlDefinition;
    private javax.swing.JTextArea txaDefinition;
    private javax.swing.JTextArea txaExample;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
